name: CI/CD Docker to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/login-action:latest
        
    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.3' # Puedes usar la versión de kubectl que necesites

    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "$KUBE_CONFIG_DATA" > kubeconfig
        kubectl --kubeconfig=./kubeconfig apply -f deployment.yml