name: CI/CD Docker to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAMEE }}
        password: ${{ secrets.DOCKERHUB_TOKENN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}flichel/login-action:latest
        file: ./dev.Dockerfile # <--- Línea agregada para especificar el nombre del archivo
        
    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.3'

    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIGG }}
      run: |
        # Escribe el secreto multilínea en un archivo usando un marcador de final de archivo.
        # Esto asegura que los saltos de línea se respeten.
        mkdir -p $HOME/.kube
        echo "$KUBE_CONFIG_DATA" > $HOME/.kube/config
        
        # Aplica el archivo de despliegue a tu clúster de Kubernetes usando el archivo de configuración.
        kubectl --kubeconfig=./kubeconfig apply -f deployment.yml
