name: CI/CD Docker to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAMEE }}
        password: ${{ secrets.DOCKERHUB_TOKENN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAMEE }}/login-action:latest
        file: ./dev.Dockerfile # <--- Línea agregada para especificar el nombre del archivo



    - name: Deploy to Kubernetes
      run: |        
        # Aplica el archivo de despliegue usando la misma ruta.
        kubectl apply -f deployment.yml
